# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven for testing-examples

on:
  push:
    paths:
      - .github/workflows/testing-examples.yaml
      - testing-examples/**
  pull_request:
    paths:
      - .github/workflows/testing-examples.yaml
      - testing-examples/**

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - name: Support longpaths
        if: matrix.os == 'windows-latest'
        run: git config --system core.longpaths true

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-testing-examples-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: maven-settings-xml-action
        uses: whelk-io/maven-settings-xml-action@v4
        with:
          repositories: '[{ "id": "redhat-ga-repository", "url": "https://maven.repository.redhat.com/ga" }]'
          plugin_repositories: '[{ "id": "redhat-ga-repository", "url": "https://maven.repository.redhat.com/ga" }]'

      - name: Run ShellCheck
        if: matrix.os == 'ubuntu-latest'
        uses: ludeeus/action-shellcheck@master
        with:
          ignore: bcgithook bdd-ui kogito-quick-start-workshop offliner-maven-plugin pam-eap-setup pam-vagrant pam-quick-examples

      - name: Build testing-examples/bdd-pam-framework
        run: |
          pushd testing-examples/bdd-pam-framework/
          mvn clean install --no-transfer-progress
          popd

      - name: Build testing-examples/cucumber-testing-quick-start
        run: |
          pushd testing-examples/cucumber-testing-quick-start/
          mvn clean install --no-transfer-progress
          popd

      # Jave 8 Builds
      - name: Set up JDK 8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Build testing-examples/bdd-ui/maven-java-bdd-demo
        run: |
          pushd testing-examples/bdd-ui/maven-java-bdd-demo
          mvn -B clean package --no-transfer-progress
          popd

      # NPM Builds
      - name: Setup node Build bdd-ui
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Build testing-examples/bdd-ui/feature-file-helper-front-end
        run: |
          pushd testing-examples/bdd-ui/feature-file-helper-front-end
          npm install -g @angular/cli
          npm install
          ng build
          popd

      - name: Build testing-examples/bdd-ui/feature-file-helper-back-end
        run: |
          pushd testing-examples/bdd-ui/feature-file-helper-back-end
          npm install
          popd